<!DOCTYPE html>
<html lang="en">
<head>
    <#include "include/common_head_tpt.ftlh">
    <link href="css/error.css" rel="stylesheet" type="text/css">
    <link href="css/crud.css" rel="stylesheet" type="text/css">
</head>
<body class="layui-layout-body layui-bg-gray">
<div class="layui-fluid">
    <div class="layui-admin-error-tips">
        <i class="layui-icon" face>&#xe664;</i>
        <div class="layui-text">
            <span>暂未设置首页!</span>
            <a id="setHomePage" href="javascript:void(1);">点击进行设置</a>
        </div>
    </div>
</div>
</body>
<script src="plugin/layui/layui.js" type="text/javascript" charset="UTF-8"></script>
<script src="js/home.js" type="text/javascript" charset="UTF-8"></script>
</html>