server:
  port: 443
  servlet:
    application-display-name: '智慧机床'
    session:
      timeout: 30m
  ssl:
    key-store: /root/ssl/Tomcat/www.xigumes.com.jks
    key-store-password: fnpfdz089o0o0yv
    key-store-type: JKS
    enabled: true

spring:
  profiles:
    active: pro,database,system
  messages:
    basename: i18n/error_message
    encoding: UTF-8
  session:
    store-type: jdbc
    jdbc:
      initialize-schema: always
  freemarker:
    request-context-attribute: request
  jackson:
    time-zone: GMT+8
    date-format: 'yyyy-MM-dd HH:mm:ss'
  activemq:
    broker-url: 'mqtt://127.0.0.1:9527'
    user: factory
    password: factory!123456
logging:
  config: classpath:logback-spring.xml


