server:
  port: 80
  servlet:
    application-display-name: '智慧机床'
    session:
      timeout: 30m
    context-path: '/factory'

spring:
  profiles:
    include: database,system,pro
  messages:
    basename: i18n/error_message
    encoding: UTF-8
  session:
    store-type: jdbc
    jdbc:
      initialize-schema: always
  freemarker:
    request-context-attribute: request
  jackson:
    time-zone: GMT+8
    date-format: 'yyyy-MM-dd HH:mm:ss'
  activemq:
    broker-url: 'tcp://www.xigumes.com:61616'
    user: 'factory'
    password: 'factory!123456'
    in-memory: false
  jms:
    pub-sub-domain: true
logging:
  config: classpath:logback-spring.xml


