server:
  port: 443
  ssl:
    key-store: /root/ssl/Tomcat/www.xigumes.com.jks
    key-store-password: fnpfdz089o0o0yv
    key-store-type: JKS
    enabled: true
  servlet:
    context-path: ''

spring:
  datasource:
    url: jdbc:mysql://172.17.0.13/factory?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2b8
  web:
    resources:
      chain:
        cache: true
  activemq:
    broker-url: 'tcp://127.0.0.1:61616'
    user: 'factory'
    password: 'factory!123456'
    in-memory: false
  jpa:
    show-sql: false
  profiles:
    active: pro