<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>智能工厂</title>
<base href="${request.contextPath}/">
<link rel="shortcut icon" type="image/ico" href="image/favicon.ico"/>
<link rel="bookmark" href="image/favicon.ico"/>
<link href="css/reset.css" rel="stylesheet" type="text/css">
<link href="plugin/layui/css/layui.css" rel="stylesheet" type="text/css">
<link href="css/layui.admin.css" rel="stylesheet" type="text/css">